### ISSUE TITLE
Initialize f_re consistently when prescribing initial n_re profile

### ISSUE THREAD

**Issue by hoppe93** [chalmersplasmatheory/DREAM#103]
When prescribing an initial ``n_re`` profile, we should also allow for some way of consistently initializing ``f_re``. There is otherwise a risk that currents and densities are calculated inconsistently. One idea for initializing is to dump all particles in the ``p=pMin``, ``xi=1`` cell (or -1 if E(t=0)<0) . This is exceedingly difficult to do in the interface (since it requires knowledge of the grid cell size/volume, and must be robust against any interpolation occuring in the kernel), and so should be implemented as an option in the kernel.

**Comment by hoppe93** [comment]
This is mostly done (in a nicer way!) on ``freinit``. Some potential further improvements could be to give the option of exactly how to initialize ``f_re``. Currently, all particles are placed in the p=pMin, xi=+/-1 grid cell, but it might be interesting to also allow the user to initialize particles in all p=pMin grid cells (i.e. isotropically), or perhaps even with an specified distribution shape (which is scaled to yield the correct ``n_re``). This should be fairly easy to implement if we want it.

**Comment by Embreus** [comment]
Not sure if I can see the need for that in the short term. Or do you feel that it can be important soon? Otherwise I suggest closing this and merging the freinit branch to master (if it is ready).
