### ISSUE TITLE
Preparatory fixes for NumericalBRadialGridGenerator

### ISSUE THREAD

**Issue by Embreus** [chalmersplasmatheory/DREAM#121]
Before we implement general numerical magnetic fields, we need to fix the following issues:

**RadialGridGenerator**
- [ ] Generalize the `FindMagneticFieldExtremum` method so that it can find Bmin, Bmax and the corresponding angles for general magnetic fields (currently only symmetric ones supported)
- [x] Remove the "optimized" functions that take cos(theta) and sin(theta) as arguments. They are probably useless to NumericalB, and are no longer really used, as they were superceded by `EvaluateGeometricQuantities` which turned out to be much more efficient.

**FluxSurfaceAverager**
- [ ] It would be a pleasant surprise if FluxSurfaceAverager.avalancheDelta.cpp works correctly with NumericalB. This should be tested by extending the RunawayFluid test to a numerical grid.

I have reviewed the code of RadialGridGenerator, FluxSurfaceAverager and BounceAverager, and surprisingly this is all I could find that looked off. Otherwise it looks like everything has been prepared!

**Comment by hoppe93** [comment]
Numerical magnetic fields are now implemented.
