### ISSUE TITLE
Psi_edge in non-linear initialization

### ISSUE THREAD

**Issue by EsmeeBerger** [chalmersplasmatheory/DREAM#162]
DREAM crashes when using non-linear initialization with the wall radius not equal to the minor radius. 

In simulations where this occurs, psi_edge seems to be initialized with a value far from the value of psi_p at the outermost radius in the radial grid. Then, after the first timestep, psi_edge abruptly changes to a value close to the value of psi_p at the outermost radius. 
There is also an abrupt change in E_field and j_tot after the first timestep.

When rWall = a, psi_edge is 0 (if assuming a perfectly conducting wall), which allows the simulations to run without crashing.

The error seems to occur regardless of using toroidal or cylindrical geometry.

**Comment by hoppe93** [comment]
The ``rWall=a`` case is handled specifically in the code. When ``rWall > a``, a term ``-M*I_p`` is added to the equation, which then reads ``psi_edge = psi_wall - M*I_p``. The only potential source of error in the initialization seems to be if something is weird with the calculated inductance (which is mostly just ``log(b/a)``). We should check with GDB (or just ``printf()``) if it is fine, and if it is, try to think a bit more about how ``psi_edge``could start at a weird value.

Btw, we didn't check what ``psi_wall`` was, but if it's anything other than identically 0, something is very wrong.

**Comment by EsmeeBerger** [comment]
I checked psi_wall and it is identically 0, so we should indeed check the value of the inductance.
