### ISSUE TITLE
Numerical equilibrium fails for some diverted TCV cases

### ISSUE THREAD

**Issue by hoppe93** [chalmersplasmatheory/DREAM#189]
The bounce average module fails with a GSL quadrature error for several LIUQE reconstructions of the TCV diverted plasmas. One example of such an equilibrium is 74610 at 0.75s.

**Comment by hoppe93** [comment]
The error appears to be due to that the routine which is responsible for calculating the bounce points of any given particle (r, p, xi0) returns a lower integration limit which is greater than the upper limit. This should be straightforward to fix with a simple check and possible swap before returning, since this is contrary to what the routine is supposed to return. Apart from the order in which the integration limits are returned, they seem to be calculated correctly.

**Comment by hoppe93** [comment]
After fixing the above-mentioned error, another error was uncovered in how the bounce-averages are carried out. It seems that the errors should affect also up-down symmetric magnetic fields, and so it remains unclear how the code has functioned before. With the new fixes the numerical equilibrium seems to work well.

**Comment by Embreus** [comment]
Sounds scary! Good catch. I always had the feeling that I never got that part entirely robust.
