### ISSUE TITLE
Implement radial transport module in DREAM!

### ISSUE THREAD

**Issue by Embreus** [chalmersplasmatheory/DREAM#20]
It is time for radial transport! Here we can track ideas for features that should be included.

The basic feature should be radial advection and diffusion terms for heat, kinetic electrons and poloidal flux that have _prescribed_ transport coefficients as (r,t) data, where the coefficients are provided by the interface. There should be settings to control the momentum dependence of the kinetic transport coefficients.

The interface could be equipped with a TransportHandler which is similar to the CollisionHandler, equipped with functions to generate transport coefficient data.

**Comment by hoppe93** [comment]
@Embreus on the topic of what should go into ``transport`` before merging: should ``psi_p`` also have a prescribed transport term? Or do we want to make it more sophisticated?

**Comment by Embreus** [comment]
I'm not sure. There already is a `HyperresistiveDiffusionTerm` (under src/Equations/PoloidalFlux) that was designed for this purpose, which is applied in E_field.cpp. In the end it is essentially just a prescribed transport though, with some geometric factors included. It is supposed to be a transport term added to the E_field equation which acts on j_tot - maybe the prescribed transport term can achieve this just as well?

**Comment by hoppe93** [comment]
Implemented and merged to master in ae24514741aee86f20e8a03cb00f7903d3a02b08
