### ISSUE TITLE
Parallel version of runiface()

### ISSUE THREAD

**Issue by hoppe93** [chalmersplasmatheory/DREAM#210]
A parallel version of the ``runiface()`` function could possibly be implemented relatively straightforwardly. One would want to utilize that ``subprocess.Popen()`` launches processes in the background and would allow us to launch multiple processes simultaneously.

By constructing two lists: one for the ``DREAMSettings`` objects yet to be run, and one list for the processes currently executing. In a loop we would make sure that the latter list always contains a set number of elements (as long as their are ``DREAMSettings`` remaining in the queue). Within the loop we would also call ``p.communicate()`` on each of the executing processes with a short timeout. Once a process finishes, we remove it from the list of executing processes and replaces it with a new.

**Comment by Pinfar** [comment]
Hi, I started working on this issue and created first implementation (https://github.com/Pinfar/DREAM/tree/parallel-runiface). I have a little problem with creating a test case for parallel processing. Do you maybe have an idea about experiment that takes very little code to set up and verify? I'd like to create about 10-20 similar experiments and run them in parallel.

**Comment by hoppe93** [comment]
Probably the most convenient example is ``examples/runaway/basic.py``. You'll just want to replace the last line (``ds.save(...)``) with a call to ``runiface()`` (needs to be imported as ``from DREAM import runiface``).

**Comment by Pinfar** [comment]
Ok, I created test here: https://github.com/Pinfar/DREAM/blob/f254f28aee55c227980ad0c51d15530ea05261e4/tests/physics/runiface_parallel/runiface_parallel.py . But now I am still not checking if the results I receive are not corrupted in some way. Maybe I can only run experiments via regular runiface and compare results with the parallel one? Which parameters should I compare?

**Comment by hoppe93** [comment]
Sorry for the long silence! I've been moving from Switzerland to Sweden and have had some very busy weeks :P I should hopefully be more responsive from now on.

Nicely done! This looks pretty much like I imagined. For the last pieces of the test, comparing to a single run with ``runiface()`` could be a good idea. I would compare either ``do.eqsys.n_re[-1,0]`` or ``ds.other.fluid.runawayRate[-1,0]``. The latter is a numerical derivative of the former so checking just one should be fine.

**Comment by Pinfar** [comment]
Hey, thanks for your response. I'll implement checks after the weekend and let you know. I also need to implement timeout parameter support. Do you think that this should be timeout for one operation or whole process?

**Comment by hoppe93** [comment]
Great, thanks! The timeout parameter is something we use as a an upper limit on simulations to tell when a simulation is non-convergent. So it should be applied to individual simulations/processes (so, for each ``DREAMTask``, I guess you'll want to accumulate the timeout given to ``self.p.communicate()`` and add a check for when the accumulated timeout for that task exceeds the user-imposed timeout).

**Comment by Pinfar** [comment]
Ok, I added implementation of timeout and comparison between serial and parallel runiface results. I am thinking about changing one more thing. Now, If any of executed experiments timeouts, then whole runiface execution throws an error. Maybe we can return other object instead of DREAMOutput?

**Comment by hoppe93** [comment]
Yes, that's a good idea! Generally, I think the application of this would be to run massive scans, and then if one simulation fails, it would be better to keep the others running and just eventually return an error for the failed simulation.

One idea could be to return a ``DREAMException`` (or perhaps a new type of exception, derived from ``DREAMException``) instead of a ``DREAMOutput`` object. The exception object could contain the ``DREAMSettings`` object which resulted in the failure as well as maybe an error code and whatever was read from stdout/stderr of the failing process?

**Comment by Pinfar** [comment]
Hey, I pushed new changes. Have a look and If you don't have any additional ideas, I will create Pull Request.

**Comment by hoppe93** [comment]
I've had quick look, and spontaneously I think everything is there (great job!). If you do the pull request it will be easier for to check in detail though.

**Comment by Pinfar** [comment]
Ok, I created https://github.com/chalmersplasmatheory/DREAM/pull/222

**Comment by hoppe93** [comment]
Merged to master in #222

**Comment by Pinfar** [comment]
If you have any other issues to solve, in this or other project, just let me know :)

**Comment by hoppe93** [comment]
Thanks! Your help is really appreciated! :) I might have another idea in mind which you could probably help with (a testing framework for full simulations), but I think I need to think through the structure a bit first. I'll try to open an issue soon to gather ideas, and then your welcome to join and contribute
