### ISSUE TITLE
SolverNonlinear: add features to IsConverged() 

### ISSUE THREAD

**Issue by Embreus** [chalmersplasmatheory/DREAM#23]
It would be good if special conditions could be given for various unknowns in IsConverged. For example, we may want to add an absolute threshold to n_re for stability in certain situations, and ignore the new particle source amplitude altogether (as it will naturally fluctuate around machine precision when the total density should be constant, and in general we don't care about it if the densities behave well -- this is now blocking my WIP commit from being robust which is annoying).

**Comment by hoppe93** [comment]
With 082969c7d7e2ac234e7ba50bb4ba4c2cee670f97 it is now possible to exclude unknowns from the convergence check.

What was the purpose of my second bullet-point?

**Comment by Embreus** [comment]
Not sure?

**Comment by Embreus** [comment]
Seems like this issue was resolved.
