### ISSUE TITLE
AvalancheGrowthTerm: inconsistencies in kinetic mode

### ISSUE THREAD

**Issue by hoppe93** [chalmersplasmatheory/DREAM#24]
The ``SetDiffWeights()`` and ``SetWeights()`` methods in [include/DREAM/Equations/Fluid/AvalancheGrowthTerm.hpp](https://github.com/chalmersplasmatheory/DREAM/blob/master/include/DREAM/Equations/Fluid/AvalancheGrowthTerm.hpp) seem to introduce particles isotropically when applied to a kinetic grid (I thought we said particles should be introduced at ``xi=1``?). They do not however take the grid size into account, which should lead to strong non-conservation of particles in the simulation. Also, since ``dGamma`` is an array of size ``nr``, the current implementation appears to lead to an index-out-of-range error when applied to a kinetic grid.

Probably, the loop on line 25 should be removed, and the indexing on line 26 should be changed to
```c++
diffWeights[offset + n1[ir]*(n2[ir]-1)] = scaleFactor*dGamma[offset]
```
(with some additional geoemtric factor for particle conservation) so that particles are introduced in ``p=0`` at ``xi=1``.

**Comment by Embreus** [comment]
Closing this now as #26 will solve this issue.
