### ISSUE TITLE
New RunawaySourceTerm class

### ISSUE THREAD

**Issue by Embreus** [chalmersplasmatheory/DREAM#26]
Source terms in the n_re equation should be derived from a new RunawaySourceTerm class instead of EquationTerm. This will allow the f_re equation to easily access the net runaway growth due to sources for the lower external boundary condition.

**Comment by hoppe93** [comment]
Add all particles to xi=1 for all terms (if E>0, otherwise in xi=-1).

**Comment by Embreus** [comment]
fixed in #82
