### ISSUE TITLE
Uninitialized values in HotTailCurrentFromDistributionFunction.cpp

### ISSUE THREAD

**Issue by hoppe93** [chalmersplasmatheory/DREAM#28]
Valgrind reports that  the first and last elements of ``Delta_p`` are uninitialized. I added a temporary fix, but I am not sure what the purpose of this variable is (it seems it's supposed to just be a copy of ``MomentumGrid::dp1``, so maybe we could get rid of it altogether?).

**Comment by Embreus** [comment]
This equation term has been reworked as of e043188 (on development branch), and the abovementioned problems have all been resolved.
