### ISSUE TITLE
Pitch grid edges deallocated from memory if using `ds.hottailgrid.setCustomGrid(xi_f=...)` resulting in error in ther `dreami` executable

### ISSUE THREAD

**Issue by leferi99** [chalmersplasmatheory/DREAM#293]
The error was
```
*** Error in `/DREAM/build/iface/dreami': double free or corruption (!prev): 0x0000000001de6f40 ***
```
The problem was in line 25 in "fvm/Grid/PXiGrid/XiCustomGridGenerator.cpp". Commenting this line and rebuilding DREAM fixed this issue.

**Comment by hoppe93** [comment]
Also the ``PCustomGridGenerator`` class has the same bug.
