### ISSUE TITLE
Specify optional ID to "Operator::AddTerm()"

### ISSUE THREAD

**Issue by hoppe93** [chalmersplasmatheory/DREAM#32]
This could allow us to easily identify different ``EquationTerm``s across the code and pick out contributions from individual terms in, for example, the ``OtherQuantityHandler``.

**Comment by hoppe93** [comment]
@vaoskar I have implemented a new way of accessing individual ``EquationTerm``s now and pushed to the branch iss-32-42. Once we have fixed the bugs currently preventing the examples from running, would you mind having a look and verifying that I implemented the other quantity ``fluid/radiation`` correctly?

**Comment by Embreus** [comment]
Fixed by #53.
