### ISSUE TITLE
Bounce averaged kinetic equation 

### ISSUE THREAD

**Issue by Embreus** [chalmersplasmatheory/DREAM#39]
Implement the boundary conditions in the kinetic equation corresponding to magnetic trapping when considering inhomogeneous magnetic fields.

**Comment by Embreus** [comment]
My latest idea for how to do this is simply to override the kinetic equation for all negative pitches which are trapped, 
   -xi_T < xi < 0,
where xi_T is the trapped-passing boundary in pitch. For such xi, the equation should read
    f(xi) = f(-xi).
With this modification, I think that everything else would fall into place automatically. (?)

**Comment by Embreus** [comment]
Ah, one more detail before all trapped negative-xi rows are nulled in the equation system. The flux from the last (negative xi) non-trapped cell into the trapped -xi_T cell must be added into the last trapped cell at +xi_T so that this particle flux doesn't just vanish.

**Comment by Embreus** [comment]
Another detail we need to work out:

On the trapped-passing boundary, Vp jumps by a factor of two since suddenly the orbits are twice as long (the barely trapped orbit goes from -pi+eps to pi-eps, _and then back again_, whereas a barely passing orbit just goes from -pi to pi when it is back to the starting point). Sometimes I've understood that it is conventional to divide the trapped bounce integrals by two for this reason to make it continuous.

Typically, for the FVM cell averages well inside the respective region this doesn't matter because we divide by Vp, and a constant factor cancels out. However, for a cell crossing the trapped-passing boundary it seems that this factor of 2 will matter in the AdvectionDiffusionTerm? In that case the Vp in the numerator (which will be evaluated on the other side of the boundary) will differ by a factor of two with the denominator, and would influence the dynamics in the boundary cell.

Which way is correct? Is it a matter of taste?

**Comment by Embreus** [comment]
TODO: implement a more careful evaluation of Vp on the trapped-passing boundary which resolves the logarithmic divergence (by carrying out an adaptive integration over xi0 over the cell and then dividing by dxi0).

**Comment by Embreus** [comment]
I am putting together a note where I outline some conditions for flux conservation on the trapped-passing boundary. As is done in LUKE and CQL3D, it appears wise to choose the pitch grid such that there is a cell center on each of the trapped-passing boundaries (one at each radius) and to have a cell face at xi=0. 

[trappedbc.pdf](https://github.com/chalmersplasmatheory/DREAM/files/5315087/trappedbc.pdf)

**Comment by Embreus** [comment]
I updated `doc/notes/trappedbc.tex` with a more explicit condition for the boundary condition, see page 2 after Eq (10). 

I think that it could be useful if `Grid` was equipped with the functionality to access which indices should be mirrored, and the mirrored cell index to which the fluxes should be added instead. This would help avoid parallel implementation (such as currently in `PxiExternalKineticKinetic` and `PXiInternalTrapping`) and ensure consistency.

**Comment by Embreus** [comment]
> I think that it could be useful if `Grid` was equipped with the functionality to access which indices should be mirrored, and the mirrored cell index to which the fluxes should be added instead. This would help avoid parallel implementation (such as currently in `PxiExternalKineticKinetic` and `PXiInternalTrapping`) and ensure consistency.

fixed this in e0b76a0. This is starting to look pretty darn good now!

**Comment by Embreus** [comment]
As far as I can tell, now it only remains to implement the mirroring of radial fluxes, and to put together a test. Perhaps to verify the radial dependence of conductivity, which should go like RadialGrid::effectivePassingFraction. Optionally, we may compare the avalanche growth rate (or dreicer) with one or more of Rosenbluth-Putvinski, ARENA, Emelie or McDevitt.

**Comment by Embreus** [comment]
The mirroring of radial fluxes has been implemented a7ac6f5. However, I don't think that any of the present tests would catch an error in this part of the code.

Therefore, it remains to implement unit and physics tests before we are ready to merge.

**Comment by hoppe93** [comment]
Great! My pull request for the ``OutputGenerator`` and friends was something I needed for the ``trapping_conductivity`` test I also started on. Should be finished soon enough...

**Comment by Embreus** [comment]
I'll declare this completed now. =) there is still the problem of #98, but let's take that discussion there.
