### ISSUE TITLE
Calculation of two alternative fluid avalanche formulae

### ISSUE THREAD

**Issue by vaoskar** [chalmersplasmatheory/DREAM#40]
The RunawayFluid-class now calculates both the avalanche formula originally introduced in DREAM and the formula published by Hesslow et al NF 2019. It would be better to implement some option-functionality to avoid the double work, since this slows down fliud simulations significantly (the evaluation of pStar in particular). Now it is also ambiguous from which model the critical momentum should be taken

**Comment by Embreus** [comment]
What do you mean by the last part, ” Now it is also ambiguous from which model the critical momentum should be taken”?

**Comment by Embreus** [comment]
I like the solution in the SPI branch now, where we do not store the ’alternative’ formula. The only situation where you would want both is for testing, and then you could rather run DREAM multiple times. Let’s stick with this way of doing it (and update the avalanche test to run single-step fluid simulations to generate the growth rate data).

**Comment by Embreus** [comment]
Modified Oskar's solution slightly so that a critical momentum is always calculated (otherwise we couldn't use compton source without using avalanche). Fixed in a77e887.
