### ISSUE TITLE
Implement compton-source as a ComplexDiagonalTerm

### ISSUE THREAD

**Issue by vaoskar** [chalmersplasmatheory/DREAM#41]
The compton source is now added as a term to an operator operating on n_re, and since it is not linear in n_re it does not contribute to the matrix when using the linear solver but is only added to the right hand side. It would be better to create another operator that operates on n_tot, and implement the compton source as a term in that operator as a ComplexDiagonalTerm.

**Comment by Embreus** [comment]
Agreed! Want me to look into it, or do you want to do it?

**Comment by Embreus** [comment]
Fixed by Oskar in 0430e25
