### ISSUE TITLE
Kinetic model of ionisation

### ISSUE THREAD

**Issue by Embreus** [chalmersplasmatheory/DREAM#46]
We should develop a kinetic model of ionisation rates I = I_i(p), satisfying
![\begin{align*}
\int I_i(p) f_M(p;\,T) \,\mathrm{d}p = I_i(T)
\end{align*}
](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0A%5Cint+I_i%28p%29+f_M%28p%3B%5C%2CT%29+%5C%2C%5Cmathrm%7Bd%7Dp+%3D+I_i%28T%29%0A%5Cend%7Balign%2A%7D%0A)
where I_i(T) is the ADAS ionisation rate coefficient for ion i and f_M a Maxwellian distribution at temperature T, which should be approximately satisfied at all temperatures T for which ADAS has data. The kinetic ionisation rate I_i(p) should depend on ion species (atomic number Z and charge Z0) but not temperature. Here we neglect the density effect that is included in the ADAS data, and we should therefore match the ADAS coefficients in the limit of zero density (OR let the kinetic ionisation rate formula be density dependent, but that seems significantly more complicated).

This would allow us to replace fluid ionisation rates by this kinetic description of ionisation, except for when the bulk is not resolved (i.e. `collfreq_mode` SUPERTHERMAL or hottail grid disabled in which case the fluid contribution should be added).

We would still use fluid recombination, since I am not aware of a good kinetic model for it, and the recombination cross section would decay rapidly with energy and thus be uninteresting for fast electrons.

**Comment by Embreus** [comment]
The idea I have for the implementation is as follows (partly outlined in doc/notes/theory):

The seminal [Burgess & Chidichimo](https://academic.oup.com/mnras/article/203/4/1269/1029856) paper (which for example is used in the FLY Los Alamos atomic physics code) gives the electron impact ionization cross section as

<img src=
"https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0A%5Csigma_%7BZ_0%2C%5Calpha%5Cto+Z_0%2B1%7D%5E%5Ctext%7BNR%7D+%26%3D+%5Cpi+a_0%5E2+C+%5Cmathcal%7BN%7D_%5Calpha+%5Cleft%28%5Cfrac%7B%5Ctext%7BRy%7D%7D%7B%5CDelta+I_Z%5E%5Calpha%7D%5Cright%29%5E2%5Cfrac%7B%28%5Cln+U%29%5E%7B1%2B%5Cbeta%5E%5Cstar%2FU%7D%7D%7BU%7D+%5C%5C%0AU+%26%3D+%5Cfrac%7Bp%5E2%7D%7B2m%5CDelta+I_Z%5E%5Calpha%7D%0A%5Cend%7Balign%2A%7D%0A" 
alt="\begin{align*}
\sigma_{Z_0,\alpha\to Z_0+1}^\text{NR} &= \pi a_0^2 C \mathcal{N}_\alpha \left(\frac{\text{Ry}}{\Delta I_Z^\alpha}\right)^2\frac{(\ln U)^{1+\beta^\star/U}}{U} \\
U &= \frac{p^2}{2m\Delta I_Z^\alpha}
\end{align*}
">

where Delta I_Z and N_a are the ionisation energy and occupation number of an atomic subshell, respectively, and C an undetermined order-unity constant (with recommended value ~2), and the expression should be summed over the subshells of the ion (typically the dominant contribution arising from one or two shells). The problem is that the ionisation energy is quite complicated, because sometimes it should be taken as an excitation energy needed for secondary (Auger) ionization and sometimes the binding potential of the ion. The parameter beta^star can be modelled as prescribed in the paper and describes a near-threshold modification to the cross section. Given these parameters, the [Garland](https://aip.scitation.org/doi/full/10.1063/5.0003638?casa_token=FR5WumtnCJQAAAAA%3A3KFy45NfUPPLmBjzO-f4Y3yEmKZ_Y-ShUojk-s4NdQHYB7_EXSNSgOI02PzxfJbaxb_nEpRUbq3sEQ) model describes how the validity of the formula can be extended to relativistic energies.

Rather than figuring out exactly how these parameters should be picked for each ion, and hoping that the result will match ADAS, I propose that we _fit_ coefficients in the formula to ADAS data. Then, we could modify `get_adas.py` such that for each ion that it downloads temperature data for, it also performs a non-linear least-squares fit of the above formula (integrated over a maxwellian at each temperature) and saves the resulting coefficients.

**Comment by Embreus** [comment]
I have investigated the Burgess & Chidichimo formula above (extended according to Garland), and took C*N_a, Delta I_Z and beta^star as 3 free parameters that were fitted to ADAS data after integrating the cross-section over a Maxwellian. This model seems to work really well (typical errors at most around tens of %, spanning tens of orders of magnitude in ionization rates), even without summing over multiple shells.

Therefore, I think that we should move forward with this simple model, as it appears to adequately cover the entire ADAS range and would give a fully kinetic description valid at all energies.

I will start the implementation of the equation term in the DREAM kernel and work out a data structure for these fit-coefficents. Using hardcoded values for argon from my test script I will try to explore the consequences of using kinetic rather than fluid ionization; hoping that this may stabilize some scenarios that wouldn't converge before.

**Comment by Embreus** [comment]
I have finally implemented the source, but using placeholder hardcoded coefficients for only H, Ne and Ar. I use the full f_hot jacobian, which turns out to be ridiculously expensive.
I propose an approximation where we use the ADAS IonRateEquation jacobian, but the kinetic vectorelements (possibly with an additional approximate nhot jacobian)

**Comment by Embreus** [comment]
This now works as intended as far as I know. It remains to add the corresponding binding-energy heating term into the T_cold equation, in the form of an update to the IonizationHeatingTerm which was supposed to fill this purpose. This is annoyingly tricky, because the ADAS part of the ionization coefficient should not be added (since it is accounted for via the RadiatedPowerTerm). We therefore probably wish to subtract the ADAS rates from the net kinetic rates in this term.

**Comment by Embreus** [comment]
Fixed the approximate jacobian. Only remains to implement updated kinetic rate coefficients to achieve higher accuracy and with more elements.

**Comment by hoppe93** [comment]
(Closing, as this has been available in DREAM for quite a while now)
