### ISSUE TITLE
Add descriptions to unknowns in the DREAMOutput

### ISSUE THREAD

**Issue by Embreus** [chalmersplasmatheory/DREAM#47]
When printing unknowns, such as
`do.eqsys.psi_p`
it would be useful if it could give not only `"psi_p: Fluid quantity of size ..."` but also a brief description of what the unknown represents and its dimension, in this case (for example)
`psi_p: Poloidal flux normalized to major radius R0 [W/m]. Fluid quantity of size...`

**Comment by Embreus** [comment]
I think that a logical place to insert the descriptions could be in Output/EquationSystem.py when setting the SPECIAL_TREATMENT's?
@hoppe93

**Comment by hoppe93** [comment]
Sounds like a good idea! Either in ``Output/EquationSystem.py`` or directly in the kernel? It is possible to add "attributes" to output data (this is how we add descriptions to ``OtherQuantity``s), and then we should perhaps specify the description of the quantity when we define it in the kernel?

On a pretty related note, we could perhaps also write the description of the equation used as an attribute for the unknown to the output file? We already have that description so it should be a simple matter to also store it in the output.

**Comment by Embreus** [comment]
I like that idea too. Automatically print both definition and equation then? Would be neat I think!

**Comment by hoppe93** [comment]
@Embreus I just implemented this using attributes in the kernel. Descriptions are defined in ``src/Settings/Constants.cpp``. Feel free to update them if you feel you have better ideas for what they should say!

The description of the equation used is also saved as an attribute. The two are available from any ``UnknownQuantity`` via
```python
E_field.description
E_field.description_eqn
```
and similar for all other unknowns. They are both included in the string version of the unknowns.
