### ISSUE TITLE
'description' missing from ion charge state densities

### ISSUE THREAD

**Issue by hoppe93** [chalmersplasmatheory/DREAM#50]
It seems that when trying to print ion charge state densities using
```python
>> do.eqsys.n_i['D'][0]
```
the ``FluidQuantity`` doesn't find any ``description`` property on the object and throws an exception.

**Comment by Embreus** [comment]
I thought I was being crazy when I didn't manage to print ion data yesterday. Glad to hear it's a bug. :P

**Comment by hoppe93** [comment]
Hmm... I cannot reproduce this on master now. Was it perhaps fixed on some other branch which has now been merged to master?

**Comment by Embreus** [comment]
I still get this error on development (which is synced with the latest master) now when i run the runaway/basic example.
