### ISSUE TITLE
Several examples crash on master

### ISSUE THREAD

**Issue by hoppe93** [chalmersplasmatheory/DREAM#52]
It seems that at least the 'consistentE', 'compton' and 'thermalquench' examples crash when run on current master. All however seem to run on the 'runawaybc' branch.

**Comment by Embreus** [comment]
I cannot reproduce this. Any more details?

**Comment by hoppe93** [comment]
This is weird :P This occured last night on my computer, on a freshly checked-out and pulled master. But now I can't reproduce it on a freshly cloned master on my work computer. I'll have to further debug when I get home...

**Comment by hoppe93** [comment]
This bug remains on one of my computers on a fresh master. I also tried to update and rebuild PETSc, but to no avail. Will keep debugging...

**Comment by hoppe93** [comment]
Seems to have been due to an error in the ADAS data. Removing the cached data and re-running ``tools/get_adas.py`` seems to have solved the issue.
