### ISSUE TITLE
Implement analytic runaway distribution function

### ISSUE THREAD

**Issue by Embreus** [chalmersplasmatheory/DREAM#54]
When the runaway grid is disabled and we only have fluid runaways, implement support to take approximate moments of the runaway population in `MomentQuantity` (and derived) `EquationTerm`s. This would be used to evaluate the RE contribution to
- `CurrentDensityFromDistributionFunction`
- `CollisionalEnergyTransferKineticTerm`
- `IonKineticIonizationTerm`

A function to evaluate an analytic runaway distribution could be implemented in the `RunawayFluid` class, where we already implement the pitch-angle distribution for the Eceff calculation. We would probably approximate the energy spectrum with the exponentially decaying steady-state avalanche formula:
![\begin{align*}
F(p) = \exp\left( - \frac{\Gamma_\mathrm{ava}}{E-E_c^\mathrm{eff}} p  \right)
\end{align*}
](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0AF%28p%29+%3D+%5Cexp%5Cleft%28+-+%5Cfrac%7B%5CGamma_%5Cmathrm%7Bava%7D%7D%7BE-E_c%5E%5Cmathrm%7Beff%7D%7D+p++%5Cright%29%0A%5Cend%7Balign%2A%7D%0A)
and normalize the function in such a way that it integrates to n_re.

**Comment by Embreus** [comment]
Presumably, these equation terms would treat the analytic RE distribution as a special case where they integrate it adaptively with a gsl quadrature.

**Comment by Embreus** [comment]
Actually, this issue may synergise quite well with #31. 

In the analytic pitch distribution appears the factor
![\begin{align*}
\int_{\xi_0}^1 \mathrm{d}\xi_0 \, \frac{\xi_0}{\langle \xi\rangle }
\end{align*}
](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0A%5Cint_%7B%5Cxi_0%7D%5E1+%5Cmathrm%7Bd%7D%5Cxi_0+%5C%2C+%5Cfrac%7B%5Cxi_0%7D%7B%5Clangle+%5Cxi%5Crangle+%7D%0A%5Cend%7Balign%2A%7D%0A) 
where the integrand should be taken as 0 in the trapping region, e.g. for |xi0|<xiT. Because this will need to be evaluated a really large number of times (especially in the Eceff calculation), at each GridRebuilt we should tabulate values of this integral for various xi0 at each radial (+flux) grid point, and create splines to evaluate it. 

Next, just like the Grid objects stores various bounce averaged quantities, we could also have it store (splines of) various pitch-distribution-averaged quantities. That is, for a set of bounce averaged quantities {X} that we need in our calculations, we also create splines that allows us to evaluate 
![\begin{align*}
\{\{ X \}\} =C \int_{-1}^1 \mathrm{d}\xi_0 \, \{X\} \exp \left( -A \int_{\xi_0}^1 \mathrm{d}\xi_0 \, \frac{\xi_0}{\langle \xi\rangle } \right)
\end{align*}
](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0A%5C%7B%5C%7B+X+%5C%7D%5C%7D+%3DC+%5Cint_%7B-1%7D%5E1+%5Cmathrm%7Bd%7D%5Cxi_0+%5C%2C+%5C%7BX%5C%7D+%5Cexp+%5Cleft%28+-A+%5Cint_%7B%5Cxi_0%7D%5E1+%5Cmathrm%7Bd%7D%5Cxi_0+%5C%2C+%5Cfrac%7B%5Cxi_0%7D%7B%5Clangle+%5Cxi%5Crangle+%7D+%5Cright%29%0A%5Cend%7Balign%2A%7D%0A)
at arbitrary values of 0 < A < inf, where A is the pitch-distribution width parameter and C=C(A) a normalization such that {{1}}=1. 

Actually, we should let RadialGrid store all of these spline objects, since they are independent of the chosen momentum grid, and will be used in a similar way by both RunawayFluid and by each kinetic Grid. RunawayFluid could implement a static method that evaluates the pitch distribution (being provided the necessary geometric quantities/spline objects by the caller) by choosing the appropriate value for A given the plasma parameters and a momentum.

**Comment by hesslow** [comment]
Suggest such function could be implemented in the class `AnalyticDistribution`, where the analytic pitch distributions have now moved.

**Comment by Embreus** [comment]
The energy distribution that is used in the new SvenssonTransport term should be the one implemented in this AnalyticDistributionRE. In this case we need to also evaluate the radial derivative for the distribution function.

**Comment by Embreus** [comment]
The suggested functionality in this issue should be generalized to support multiple different analytic distributions. For example, for fluid hot tail simulations we  want to also have an analytic (isotropic) f_hot distribution, which should also be evaluated with the mentioned MomentQuantity's.
