### ISSUE TITLE
Rework flux surface integrals in RadialGridGenerator

### ISSUE THREAD

**Issue by Embreus** [chalmersplasmatheory/DREAM#56]
Currently, the various implementations of the `RadialGridGenerator` implement a function `CreateMagneticFieldData` which generates magnetic field and jacobian data on a reference grid. Then, the `FluxSurfaceAverager` interpolates in this reference data to perform flux surface averages. 

It would make more sense to let `RadialGridGenerator` be equipped with functions like 
`EvaluateJacobianAtTheta(len_t ir, real_t theta)`
`EvaluateBAtTheta(len_t ir, real_t theta)`
and so on that the derived classes implement, and that the `FluxSurfaceAverager` can call as required. Then the resolution of the reference grid will not affect our solutions, which is an undesired drawback of the present method.

**Comment by Embreus** [comment]
Also make the shape profiles in AnalyticB (kappa, delta, ...) `Interpolator1D` objects which are loaded from settings. Some modifications will be needed since the `RadialGrid` doesn't yet exist when these are created. 

The `fvm/fluxsurfaceaverage` test will need to be modified as well with this change.

**Comment by hoppe93** [comment]
Didn't we decide on *not* using ``Interpolator1D`` for the shape profiles? The ``Interpolator1D`` is intended for interpolating data in time, but we probably want static profiles. Instead we would want to interpolate the profiles when loading the data from file (something I can surely help with!).

**Comment by Embreus** [comment]
Yes, indeed. It would be nice if we could come up with a `GridRebuilt`-compatible solution where it can be reinterpolated if the grid changes.

**Comment by Embreus** [comment]
I implemented the first bit of this issue in 493665e.
It remains to sort out the shape profiles and interface. An idea I had was to replace the ”psi” profile (ie the reference poloidal flux which sets the poloidal magnetic field strength) with a current profile, which would be more tangible and from which the required psi profile can be calculated.

_Hmm, do/should we support the AnalyticB field in SOFT?_
