### ISSUE TITLE
Option in interface to save PETSc matrix

### ISSUE THREAD

**Issue by hoppe93** [chalmersplasmatheory/DREAM#65]
We should add an option to the Python interface which allows us to save the PETSc matrix and/or Jacobian during a solve to disk. This is often used when debugging, and currently we have to manually insert ``Matrix->View()`` where desired in the code (which is usually in the same place, in the solvers).

**Comment by Embreus** [comment]
Could be useful to add a simple counter for how many times the matrix has been rebuilt, and be able to choose after how many rebuilds it should be saved. And a flag for whether to terminate the simulation after saving?

**Comment by hoppe93** [comment]
Implemented in 371665b01b1ad5831ddbfc756b57760b5c61776e. The matrix/jacobian/RHS/residual/numerical jacobian can be saved either in a single specified time step/iteration, or in every time step/iteration. All options are set using the ``setDebug()`` method of the ``Solver`` object in the Python settings interface.

(I think it's more efficient to let the user manually terminate the code when desired instead of introducing an option for doing this in the debugging interface, hence I didn't implement it exactly as suggested)

**Comment by Embreus** [comment]
Sounds great!
