### ISSUE TITLE
Add lost density as OtherQuantity

### ISSUE THREAD

**Issue by hoppe93** [chalmersplasmatheory/DREAM#66]
When running with lossy boundary conditions for the radial transport we should calculate and store the number of particles which are lost in each time step as an ``OtherQuantity``. It should be possible, and rather straightforward, to obtain this by calling ``AddVectorElements()`` on the ``BoundaryCondition`` for the transport. The lost density is then obtained as this value multiplied by ``VpVol*dr``.

**Comment by Embreus** [comment]
This would go hand in hand with an equation term we need for the new particle source. Let’s discuss this at the next opportunity.
