### ISSUE TITLE
Put hyperresistivity term in transport term

### ISSUE THREAD

**Issue by Embreus** [chalmersplasmatheory/DREAM#79]
We should put `HyperresistiveDiffusionTerm` inside `ConstructTransportTerm`, and have its diffusion coefficient (the current input `Lambda`) be set either by dB/B (according to section 5.4 in doc/notes/theory) or directly as an input.

Perhaps we could also replace the arguments `bool kinetic`, `bool heat` to `ConstructTransportTerm` by an `enum transportType` or similar, that could be for example `TRANSPORT_TYPE_DENSITY`/`HEAT`/`KINETIC`/`POL_FLUX`?

**Comment by hoppe93** [comment]
The hyperresistive diffusion term has now been added to the code, albeit in a slightly different way (i.e. not part of the general transport interface).
