### ISSUE TITLE
Probable memory problem (all quantities suddenly -nan)

### ISSUE THREAD

**Issue by boelb** [chalmersplasmatheory/DREAM#81]
Two attempts at simulation with prescribed exponential temperature drop. The simulations included hot-tail grid (kinetic avalanche source) and added neutral argon (fully dynamic). 
On first attempt, DREAM exited without error message on timestep 531 of 1000. At first, I suspected this might be to an incorrect temperature matrix (defined so that the temperature drop ended up happening awfully fast). The second attempt had a correct temperature matrix (although defined at other times than the those in the simulation time vector). On time step 402 (of 500), Newton iteration 3, all quantities suddenly became -nan. It turned out 100% of the memory was being used. After killing DREAM, memory usage dropped to 9.3%.

**Comment by Embreus** [comment]
any progress on this? I really don't know what may be going on here.

**Comment by hoppe93** [comment]
I think these are two separate issues. The memory issues is one we were bound to run into eventually (and which we have prepared for fixing), which is that you can only store so many time steps before the computer runs out of memory. One fix for this is provided in dc319c0 which introduces the possibility of downsampling the saved time steps (with the constant time stepper).

The other issue, which gives all elements NaN, is an issue with MUMPS. It is not entirely clear to me exactly why MUMPS fails to converge, but a possible explanation is that the matrix becomes so poorly conditioned that MUMPS gives up. A potential fix for this is discussed in #87, and so I will close this issue now in favour of that one.

**Comment by hoppe93** [comment]
The memory issue seems to be remaining... Will have to debug this properly :P

**Comment by hoppe93** [comment]
Memory issue fixed in b025a058e8e9a5d6cd573741df595689bda221ab.
