### ISSUE TITLE
Implement Rebuild method in IonHandler

### ISSUE THREAD

**Issue by Embreus** [chalmersplasmatheory/DREAM#86]
Currently, when the number of ion charge states exceeds ~10 or so, the calculations of n_free and Zeff starts taking a not-insignificant fraction of the total computation time. We should give IonHandler a rebuild where it calculates and stores these quanties, and replace the `evaluate`-functions with getters.

**Comment by Embreus** [comment]
@hoppe93 where in `EquationSystem` would it be best to carry out this rebuild? At the beginning of `EquationSystem::Rebuild()`?

**Comment by hoppe93** [comment]
Certainly in ``EquationSystem::Rebuild()`` (it is called once every Newton iteration). And since both the collision quantity handlers and the RunawayFluid object depend on the ions it sounds reasonable to put it first in that method.

**Comment by Embreus** [comment]
Fixed in e105118.
